// <auto-generated />
using System;
using BikeRental.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeRental.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BikeRental.Domain.Models.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("color");

                    b.Property<int>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("model_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("serial_number");

                    b.HasKey("Id")
                        .HasName("pk_bikes");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("ix_bikes_model_id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_bikes_serial_number");

                    b.ToTable("Bikes", (string)null);
                });

            modelBuilder.Entity("BikeRental.Domain.Models.BikeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("BrakeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("brake_type");

                    b.Property<int>("MaxCyclistWeight")
                        .HasColumnType("int")
                        .HasColumnName("max_cyclist_weight");

                    b.Property<decimal>("RentPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("rent_price");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<double>("Weight")
                        .HasColumnType("double")
                        .HasColumnName("weight");

                    b.Property<int>("WheelSize")
                        .HasColumnType("int")
                        .HasColumnName("wheel_size");

                    b.Property<string>("YearOfManufacture")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("year_of_manufacture");

                    b.HasKey("Id")
                        .HasName("pk_bike_models");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_bike_models_type");

                    b.HasIndex("Type", "WheelSize")
                        .HasDatabaseName("ix_bike_models_type_wheel_size");

                    b.ToTable("BikeModels", (string)null);
                });

            modelBuilder.Entity("BikeRental.Domain.Models.Lease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BikeId")
                        .HasColumnType("int")
                        .HasColumnName("bike_id");

                    b.Property<int>("RentalDuration")
                        .HasColumnType("int")
                        .HasColumnName("rental_duration");

                    b.Property<DateTime>("RentalStartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("rental_start_time");

                    b.Property<int>("RenterId")
                        .HasColumnType("int")
                        .HasColumnName("renter_id");

                    b.HasKey("Id")
                        .HasName("pk_leases");

                    b.HasIndex("BikeId")
                        .HasDatabaseName("ix_leases_bike_id");

                    b.HasIndex("RenterId")
                        .HasDatabaseName("ix_leases_renter_id");

                    b.ToTable("Leases", (string)null);
                });

            modelBuilder.Entity("BikeRental.Domain.Models.Renter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_renters");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_renters_phone_number");

                    b.ToTable("Renters", (string)null);
                });

            modelBuilder.Entity("BikeRental.Domain.Models.Bike", b =>
                {
                    b.HasOne("BikeRental.Domain.Models.BikeModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bikes_bike_models_model_id");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("BikeRental.Domain.Models.Lease", b =>
                {
                    b.HasOne("BikeRental.Domain.Models.Bike", "Bike")
                        .WithMany()
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leases_bikes_bike_id");

                    b.HasOne("BikeRental.Domain.Models.Renter", "Renter")
                        .WithMany()
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leases_renters_renter_id");

                    b.Navigation("Bike");

                    b.Navigation("Renter");
                });
#pragma warning restore 612, 618
        }
    }
}
